 - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  - name: Update records on digital ocean
      run: |
        for file in domains/*; do
          cname=$(cat $file)
          echo $file
          echo $cname

          doctl compute domain records create --record-type CNAME --record-name $file --record-data $cname
        done